name: Release Docker Image
on:
  push:
    branches: [ ethermeta-master ]
  repository_dispatch:
  workflow_dispatch:
    inputs:
      version:
        description: 'Python Version'
        required: false
        default: '3.10'

env:
  ORG: ghcr.io/ethermeta-org
jobs:
  odoo-docker:

    name: odoo-${{ matrix.odoo_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        odoo_version: ['14.0', '15.0', '16.0']

    steps:
      - uses: actions/checkout@v3

      - name: Login to github Registry
        run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and odoo image
        run: | 
            docker build --no-cache --tag ghcr.io/ethermeta-org/odoo-docker:${{ matrix.odoo_version }} --no-cache=true .
            docker push ghcr.io/ethermeta-org/odoo-docker:${{ matrix.odoo_version }}
        working-directory: ${{ matrix.odoo_version }}
